PyTorch is a framework for building deep learning models

Useful resources:

*   Installation and Guide: https://pytorch.org
*   Course notes: https://www.learnpytorch.io
*   Course GitHub page: https://github.com/mrdbourke/pytorch-deep-learning





In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

torch_version = torch.__version__
runtime_status = !nvidia-smi

In [3]:
torch_version

'2.0.1+cu118'

In [2]:
runtime_status

['Fri Jul 14 10:02:30 2023       ',
 '+-----------------------------------------------------------------------------+',
 '| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |',
 '|-------------------------------+----------------------+----------------------+',
 '| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |',
 '| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |',
 '|                               |                      |               MIG M. |',
 '|===============================+======================+======================|',
 '|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |',
 '| N/A   37C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |',
 '|                               |                      |                  N/A |',
 '+-------------------------------+----------------------+----------------------+',
 '                                      

In [7]:
scalar = torch.tensor(7)

scalar.item(), scalar.shape, scalar.ndim

(7, torch.Size([]), 0)

In [8]:
vector = torch.tensor([1,2])

vector[0].item(), vector.shape, vector.ndim

(1, torch.Size([2]), 1)

In [10]:
MATRIX = torch.tensor([ [1, 2, 3],
                        [4, 5, 6] ])

MATRIX[0][1].item(), MATRIX.shape, MATRIX.ndim

(2, torch.Size([2, 3]), 2)

In [14]:
TENSOR = torch.tensor([   [ [1, 2], [3, 3] ],
                          [ [4, 4], [5, 6] ]   ])

TENSOR[0][0][1].item(), TENSOR.shape, TENSOR.ndim

(2, torch.Size([2, 2, 2]), 3)

In [2]:
random_tensor = torch.rand(
    size = (3,4),
    dtype = torch.float64,
    device = None, # "cpu", "cuda", etc.
    requires_grad = False
)

random_tensor, random_tensor.shape, random_tensor.dtype, random_tensor.device, random_tensor.requires_grad

(tensor([[0.3420, 0.3173, 0.4227, 0.3271],
         [0.2452, 0.3286, 0.1445, 0.6798],
         [0.4117, 0.2616, 0.0948, 0.7478]], dtype=torch.float64),
 torch.Size([3, 4]),
 torch.float64,
 device(type='cpu'),
 False)

In [3]:
zeros = torch.zeros(size=(3,4))
ones = torch.ones(size=(2,3))
x = torch.zeros_like(ones)
y = torch.ones_like(zeros)

zeros, ones, x, y

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

In [5]:
range_tensor = torch.arange(start=1, end=11, step=1)
range_tensor

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
a1 = torch.tensor([1, 2, 3])
a2 = torch.tensor([4, 5, 6])
b = torch.tensor([[1],
                 [2],
                 [3]])
print(a1+a2) # torch.add(a,b)
print(a1-a2) # torch.subtract(a,b)
print(a1*a2) # torch.multiply(a,b)
print(a1/a2) # torch.divide(a,b)
print(a1 @ b) # torch.matmul(a,b)

# torch.mm(a,b) is an alternative to torch.matmul(a,b), but it doesn't broadcast (fix the shapes)

tensor([5, 7, 9])
tensor([-3, -3, -3])
tensor([ 4, 10, 18])
tensor([0.2500, 0.4000, 0.5000])
tensor([14])


In [10]:
# transpose of a tensor
b.T

tensor([[1, 2, 3]])

In [11]:
print(torch.min(b))
print(torch.max(b))
print(torch.sum(b))
print(torch.mean(b.type(torch.float32)))
print(torch.argmin(b))
print(torch.argmax(b))

tensor(1)
tensor(3)
tensor(6)
tensor(2.)
tensor(0)
tensor(2)


In [12]:
b.dtype

torch.int64

In [15]:
# change tensor data type
b = b.type(torch.float64)

In [16]:
b.dtype

torch.float64

In [17]:
# reshaping
t = torch.arange(1,10,1) # 9 elements
reshaped = t.reshape(3,3) # 3 x 3 = 9
reshaped

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [18]:
# reshaped tensors do not always share the same memory but views do
v = t.view(3,3)
v[0][0] = 10

In [19]:
v,t

(tensor([[10,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]]),
 tensor([10,  2,  3,  4,  5,  6,  7,  8,  9]))

In [20]:
# Stacking tensors
ts = torch.stack(tensors = [t,t,t], dim = 1)

ts

tensor([[10, 10, 10],
        [ 2,  2,  2],
        [ 3,  3,  3],
        [ 4,  4,  4],
        [ 5,  5,  5],
        [ 6,  6,  6],
        [ 7,  7,  7],
        [ 8,  8,  8],
        [ 9,  9,  9]])

In [24]:
# Squeeze = eliminate 1 dimensionals
# Unsqueeze = vice-versa, add dimensionals as you wish

t = torch.tensor([[1, 2]])

sq = t.squeeze()
usq = t.unsqueeze(dim=2)

sq, usq

(tensor([1, 2]),
 tensor([[[1],
          [2]]]))

In [26]:
# Permuting
t = torch.rand(size=(300, 400, 3))

p = t.permute(2,0,1) # changes the position of sizes

p.shape

torch.Size([3, 300, 400])

In [28]:
# Indexing
t = torch.tensor([
    [
        [1,2], [3,4]
    ],
    [
        [5,6], [7,8]
    ]
])

t[:, :, 1] # or t[:][:][1]

tensor([[2, 4],
        [6, 8]])

In [31]:
# PyTorch - NumPy relationship

arr = np.arange(1,8) # ndarray
t = torch.from_numpy(arr)
arr2 = t.numpy() # if tensor is on GPU, it can't transform to numpy() array
t, arr2

(tensor([1, 2, 3, 4, 5, 6, 7]), array([1, 2, 3, 4, 5, 6, 7]))

In [30]:
# Reproducibility (flavor the randomness)
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

In [2]:
# Check if PyTorch has access to GPU
torch.cuda.is_available()

True

In [3]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [4]:
device

'cuda'

In [6]:
torch.cuda.device_count()

1

In [9]:
t = torch.tensor([7])
tensor_in_gpu = t.to(device)
tensor_in_cpu = t.cpu()
tensor_in_gpu, tensor_in_cpu

(tensor([7], device='cuda:0'), tensor([7]))

In [10]:
tensor_in_cpu.numpy()

array([7])

In [11]:
tensor_in_gpu.numpy()

TypeError: ignored